name: Feature request
description: Suggest an idea for LibPacstall
labels: ["enhancement", "triage"]
assignees:
  - wizard-28
  - D-Brox
body:
  - type: textarea
    id: problem
    attributes:
      label: Is your feature related to a problem? Please describe.
      description: A clear and concise description of what the problem is.
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Implementation reason
      description: Why do you think this should be implemented in LibPacstall and not in the clients that use this library.
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context about the feature request here.
