name: tests

on: ["push"]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@master
        with:
          python-version: 3.8
      - name: Setup Poetry Environment
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          poetry install
      - name: Test LibPacstall
        run: |
          poetry run coverage run -m pytest .
      - name: Generate Coverage Report
        run: |
          poetry run coverage report -m
          poetry run coverage xml
      - name: Upload Coverage Report to CodeCov
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true
          verbose: true
